"""
Standalone notification checks for Telegram, Email, and Google Sheets.

Expected console outputs:
- ✅ Telegram OK
- ✅ Email OK
- ✅ Sheets OK
(or ❌ with specific error text)
"""

from __future__ import annotations

import base64
import logging
import os
from datetime import datetime, timezone
from typing import Any
from dotenv import load_dotenv

from email_notifier import EmailNotifier
from google_sheets_client import GoogleSheetsClient
from telegram_bot import TelegramBot

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("test_notifications")

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))


def _load_credentials_json() -> str:
    creds_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "credentials.json")
    if os.path.isfile(creds_file):
        with open(creds_file, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if content.startswith("{"):
            return content

    raw = os.getenv("GOOGLE_CREDENTIALS_JSON", "").strip()
    if not raw:
        return ""
    if raw.startswith("{"):
        return raw

    try:
        decoded = base64.b64decode(raw).decode("utf-8")
        if decoded.startswith("{"):
            return decoded
    except Exception:
        pass

    return ""


def _build_sheets_client() -> GoogleSheetsClient | None:
    creds_json = _load_credentials_json()
    sheet_id = os.getenv("GOOGLE_SHEET_ID", "").strip()
    sa_email = os.getenv("GOOGLE_SERVICE_ACCOUNT_EMAIL", "").strip()

    if not creds_json or not sheet_id:
        return None

    try:
        return GoogleSheetsClient(creds_json, sheet_id, sa_email)
    except Exception as exc:
        log.error("Sheets client init failed: %s", exc)
        return None


def _test_telegram(bot: TelegramBot) -> tuple[bool, str]:
    if not bot.bot_token or not bot.chat_id:
        return False, "missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID"

    ok = bot.send_message(
        "🧪 Job Monitor test ping\n\nIf you received this, Telegram notifications are working."
    )
    if ok:
        return True, ""
    return False, "Telegram API call failed"


def _test_email(notifier: EmailNotifier) -> tuple[bool, str]:
    if not notifier.is_configured:
        return False, "missing EMAIL_SENDER / EMAIL_APP_PASSWORD / EMAIL_RECIPIENT"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    subject = "🧪 Job Monitor Email Test"
    html = (
        "<html><body><h3>Job Monitor Email Test</h3>"
        f"<p>Sent at {now}</p>"
        "<p>If you received this, SMTP configuration is valid.</p>"
        "</body></html>"
    )
    plain = f"Job Monitor Email Test sent at {now}."

    ok = notifier._send(subject, html, plain)
    if ok:
        return True, ""
    return False, "SMTP send failed"


def _test_sheets(client: GoogleSheetsClient | None) -> tuple[bool, str]:
    if client is None:
        return False, "missing GOOGLE_CREDENTIALS_JSON or GOOGLE_SHEET_ID"

    payload = {
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "job_title": "Test Notification Row",
        "company": "Job Monitor Bot",
        "location": "Remote",
        "job_type": "Test",
        "posted_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "apply_link": "https://example.com/test-notification-row",
        "description": "Synthetic row written by test_notifications.py",
        "matched_keywords": "test, monitoring",
        "status": "New",
        "notes": "Generated by standalone notification test",
        "ai_score": 85,
    }

    ok = client.append_job_row(payload)
    if ok:
        return True, ""
    return False, "sheet append failed"


def run_all_tests(notifier: Any | None = None) -> dict[str, bool]:
    """Run all channel tests and print one-line status per channel."""
    tg = TelegramBot()
    email = EmailNotifier()
    sheets = _build_sheets_client()

    # If monitor already built a notifier, reuse configured channels when possible.
    if notifier is not None:
        tg = getattr(notifier, "_tg", tg) or tg
        email = getattr(notifier, "_email", email) or email
        sheets = getattr(notifier, "_sheets", sheets) or sheets

    tg_ok, tg_err = _test_telegram(tg)
    email_ok, email_err = _test_email(email)
    sheets_ok, sheets_err = _test_sheets(sheets)

    if tg_ok:
        print("✅ Telegram OK")
    else:
        print(f"❌ Telegram ERROR: {tg_err}")

    if email_ok:
        print("✅ Email OK")
    else:
        print(f"❌ Email ERROR: {email_err}")

    if sheets_ok:
        print("✅ Sheets OK")
    else:
        print(f"❌ Sheets ERROR: {sheets_err}")

    return {
        "telegram": tg_ok,
        "email": email_ok,
        "sheet": sheets_ok,
    }


def main() -> None:
    run_all_tests()


if __name__ == "__main__":
    main()
